### PR TITLE
Jupyterlabforms

### PR DESCRIPTION
**Pull request by cjw85**

### CODE REVIEW

**Comment by zat89** [comment]
Hi,

After you update the notebook, i can't execute the notebook. Even i try to execute the sample data. It got stuck at "Data entry". Also, the "Data entry" panel view still like a raw python script. Not like a previous one.

Thanks.

**Comment by cjw85** [comment]
Hi @zat89,

Can you give a few more details here. Which version of EPI2MELabs Launcher and the server component are you using? We released a new one yesterday to go with the updated notebooks an move away from Google Colab (https://epi2me-labs.github.io/blog/jupytermove/).

See the downloads page here:
https://epi2me-labs.github.io/blog/downloads/

image

**Comment by zat89** [comment]
My launcher version is 0.6.1 and server version is v0.2.5.
Thanks, i'll update it now.

**Comment by zat89** [comment]
After trying install labslaucher from github or from debian, i got same error.
Here what i got:
AttributeError: Can't get attribute 'NotebookFlavour' on <module 'labslauncher' from '~/labslauncher/labslauncher/__init__.py'>

Also, the link that you provide in https://epi2me-labs.github.io/blog/nbindex/ still not accessible.

Sorry for posting different probelm here.

**Comment by cjw85** [comment]
The links on that page will be populated later next week.

Could you please open an issue at https://github.com/epi2me-labs/labslauncher/issues detailing how you have installed the launcher and how you are trying to execute it. I cannot reproduce your error using the source from github and the instructions in the README.

**Comment by zat89** [comment]
Okay, thanks for your update. I have moved the issue.

**Pull request merged**
